site_name: NovaMDR Documentation

extra_css:
  - stylesheets/extra.css

theme:
  name: material

  logo: images/logo.png
  favicon: images/logo.png

  font:
    text: Roboto

  features:
    - navigation.tabs



  palette: 
    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode


